### ISSUE TITLE
Support description metadata key for content types

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-content#3]
The [description](https://wiki.outernet.is/wiki/Content_metadata_specification#description_.28string.2C_used_in:_video.2C_audio.2C_image.2C_appdata.2C_generic.29) key is supposed to be usable in all available types, but the `meta` object does not seem to expose it. It should be made available via a property.

**Comment by integricho** [comment]
Description won't be available when doing queries of multiple items due to the performance impact of having to fetch from related tables, but will be available when fetching single items.
